name: NethVoice CTI Release on tags

on:
    push:
      tags:
        - '**'

jobs:
  release-module:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}