name: Update phone-island dependency

# **What it does**: Every nigth, at midnight checks if a new version of phone-island is available.
# **Why we have it**: To avoid manually updating the npm package.
# **Who does it impact**: package.json and phone-island dependency.

on:
  workflow_dispatch:

  schedule:
    - cron:  "0 0 * * *"

jobs:
  update-dependency:
    name: Update phone-island dependency

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Reconfigure git to use HTTP authentication and update dependency
        run: |
          git config --global url.https://${{ secrets.ICONS_TOKEN }}@github.com/.insteadOf ssh://git@github.com/
          npm update @nethesis/phone-island --save

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'build(deps): Update phone-island dependency (automated)'
          branch: 'build-update-phone-island-dependency-automated'
          commit-message: 'build(deps): NPM: update phone-island dependency (automated)'
